---
- name: Our first play
  hosts: planetexpress

  # var file   # Here is the issue - notice how the vars_files is not green? That is because it is not being treated as a key. We just need to add in a colon to fix this.
  vars_files:
    - vars/myvars.yml

  tasks:
   - name: Install installs cowsay on any host with ansible_distribution == "Ubuntu"
     apt:
       name: cowsay
       state: present
     become: yes # run as sudo
     when: ansible_distribution=="Ubuntu"
   
   - name: install figlet with "Ubuntu"
     apt: 
       name: figlet
       state: present
     become: yes #run as sudo
     when: ansible_distribution=="Ubuntu"

   - name: intatll installs cowsay on any host with ansible_distribution == "CentOS"
     yum:
       name: cowsay
       state: present
     become: yes # run as sudo
     when: ansible_distribution=="CentOS"
     # It is complaining about this when check. Stare and Compare at the difference between this when and the previous one that was working for Ubuntu. 
     
   - name: execute commands
     shell: "{{item}}"
     loop: "{{commands}}"
